# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-09 02:31
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_configuration', '0003_auto_20200805_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='values',
            field=jsonfield.fields.JSONField(default=b'{\n             "site_domain":"",\n             "PLATFORM_NAME":"",\n             "course_org_filter":"",\n             "show_only_org_on_student_dashboard":true,\n             "COURSES_ARE_BROWSABLE":true,\n             "SHOW_ILT_CALENDAR":true,\n             "email_from_alias":"",\n             "logo_image_url":"hawthorn-/images/logo.png",\n             "ENABLE_ANALYTICS":true,\n             "ENABLE_WAIVER_REQUEST":true,\n             "ENABLE_ILT_ANALYTICS":true,\n             "ENABLE_FAQ_LINK":true,\n             "ENABLE_EDFLEX_CATALOG":false,\n             "EDFLEX_URL":"",\n             "ENABLE_EDFLEX_REDIRECTION":false,\n             "EDFLEX_RENAME":"",\n             "ALLOW_PUBLIC_ACCOUNT_CREATION":false,\n             "ENABLE_DASHBOARD_BOOKMARKS":false,\n             "ENABLE_LAST_ACTIVITY":false,\n             "ENABLE_LEADERBOARD":true,\n             "ENABLE_ACCOUNT_DELETION":false,\n             "SKIP_EMAIL_VALIDATION":false,\n             "ANALYTICS_USER_PROPERTIES":{\n                  "lt_employee_id":"default",\n                  "email":"default",\n                  "gender":"option",\n                  "country":"default",\n                  "lt_area":"default",\n                  "lt_sub_area":"default",\n                  "city":"default",\n                  "location":"default",\n                  "lt_address":"option",\n                  "lt_address_2":"default",\n                  "lt_company":"option",\n                  "lt_hire_date":"option",\n                  "lt_level":"default",\n                  "lt_job_code":"default",\n                  "lt_department":"option",\n                  "lt_ilt_supervisor":"option"\n             },\n             "ILT_OPTIONAL_FIELDS":[\n                  "area_region",\n                  "address",\n                  "zip_code",\n                  "city",\n                  "location_id",\n                  "duration"\n             ],\n             "ILT_DATE_FORMAT":"DD-MM-YYYY HH:mm",\n             "ILT_DROPDOWN_LIST_FORMAT":"{area_region} - {city} - {zip_code} - {start_at} - Nb hrs. {duration} h"\n}'),
        ),
    ]