# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-08 04:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import opaque_keys.edx.django.models
import triboo_analytics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', triboo_analytics.models.AutoCreatedField(default=datetime.date.today, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('org', models.CharField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('nb_users', models.PositiveIntegerField(default=0)),
            ],
            options={
                'get_latest_by': 'created',
            },
            bases=(triboo_analytics.models.UnicodeMixin, triboo_analytics.models.ReportMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CourseDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', triboo_analytics.models.AutoCreatedField(default=datetime.date.today, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('enrollments', models.PositiveIntegerField(default=0)),
                ('average_final_score', models.PositiveSmallIntegerField(default=0)),
                ('posts', models.PositiveIntegerField(default=0)),
                ('finished', models.PositiveIntegerField(default=0, verbose_name='Successful')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='Unsuccessful')),
                ('in_progress', models.PositiveIntegerField(default=0, verbose_name='In Progress')),
                ('not_started', models.PositiveIntegerField(default=0, verbose_name='Not Started')),
                ('average_complete_time', models.PositiveIntegerField(default=0)),
            ],
            options={
                'get_latest_by': 'created',
            },
            bases=(triboo_analytics.models.UnicodeMixin, triboo_analytics.models.ReportMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LearnerCourseDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', triboo_analytics.models.AutoCreatedField(default=datetime.date.today, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('org', models.CharField(db_index=True, max_length=255)),
                ('status', models.PositiveSmallIntegerField(default=0, help_text='not started: 0; in progress: 1; finished: 2; failed: 3; ')),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('badges', models.CharField(default='0 / 0', max_length=20)),
                ('current_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('posts', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.PositiveIntegerField(default=0)),
                ('enrollment_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('completion_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created',
            },
            bases=(triboo_analytics.models.UnicodeMixin, triboo_analytics.models.ReportMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LearnerDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', triboo_analytics.models.AutoCreatedField(default=datetime.date.today, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('org', models.CharField(db_index=True, max_length=255)),
                ('enrollments', models.PositiveIntegerField(default=0)),
                ('average_final_score', models.PositiveSmallIntegerField(default=0)),
                ('badges', models.CharField(default='0 / 0', max_length=20)),
                ('posts', models.PositiveIntegerField(default=0)),
                ('finished', models.PositiveSmallIntegerField(default=0, verbose_name='Successful')),
                ('failed', models.PositiveSmallIntegerField(default=0, verbose_name='Unsuccessful')),
                ('not_started', models.PositiveSmallIntegerField(default=0, verbose_name='Not Started')),
                ('in_progress', models.PositiveSmallIntegerField(default=0, verbose_name='In Progress')),
                ('total_time_spent', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created',
            },
            bases=(triboo_analytics.models.UnicodeMixin, triboo_analytics.models.ReportMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LearnerSectionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', triboo_analytics.models.AutoCreatedField(default=datetime.date.today, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('section_key', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=512)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerVisitsDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', triboo_analytics.models.AutoCreatedField(default=datetime.date.today, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255, null=True)),
                ('org', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('device', models.CharField(max_length=255)),
                ('time_spent', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created',
            },
            bases=(triboo_analytics.models.UnicodeMixin, triboo_analytics.models.ReportMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MicrositeDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', triboo_analytics.models.AutoCreatedField(default=datetime.date.today, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('org', models.CharField(max_length=255)),
                ('users', models.PositiveIntegerField(default=0)),
                ('courses', models.PositiveIntegerField(default=0)),
                ('finished', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('average_time_spent', models.PositiveIntegerField(default=0)),
                ('total_time_spent_on_mobile', models.PositiveIntegerField(default=0)),
                ('total_time_spent_on_desktop', models.PositiveIntegerField(default=0)),
            ],
            options={
                'get_latest_by': 'created',
            },
            bases=(triboo_analytics.models.UnicodeMixin, triboo_analytics.models.ReportMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('learner_visit', models.DateTimeField(default=None, null=True)),
                ('learner_course', models.DateTimeField(default=None, null=True)),
                ('learner', models.DateTimeField(default=None, null=True)),
                ('course', models.DateTimeField(default=None, null=True)),
                ('microsite', models.DateTimeField(default=None, null=True)),
                ('country', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'get_latest_by': 'created',
            },
            bases=(triboo_analytics.models.UnicodeMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='micrositedailyreport',
            unique_together=set([('created', 'org')]),
        ),
        migrations.AlterIndexTogether(
            name='micrositedailyreport',
            index_together=set([('created', 'org')]),
        ),
        migrations.AlterUniqueTogether(
            name='coursedailyreport',
            unique_together=set([('created', 'course_id')]),
        ),
        migrations.AlterIndexTogether(
            name='coursedailyreport',
            index_together=set([('created', 'course_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='countrydailyreport',
            unique_together=set([('created', 'org', 'country')]),
        ),
        migrations.AlterIndexTogether(
            name='countrydailyreport',
            index_together=set([('created', 'org')]),
        ),
        migrations.AlterUniqueTogether(
            name='learnervisitsdailyreport',
            unique_together=set([('created', 'user', 'course_id', 'device')]),
        ),
        migrations.AlterIndexTogether(
            name='learnervisitsdailyreport',
            index_together=set([('created', 'user', 'course_id', 'device')]),
        ),
        migrations.AlterUniqueTogether(
            name='learnersectionreport',
            unique_together=set([('user', 'course_id', 'section_key')]),
        ),
        migrations.AlterUniqueTogether(
            name='learnerdailyreport',
            unique_together=set([('created', 'user', 'org')]),
        ),
        migrations.AlterIndexTogether(
            name='learnerdailyreport',
            index_together=set([('created', 'user', 'org')]),
        ),
        migrations.AlterUniqueTogether(
            name='learnercoursedailyreport',
            unique_together=set([('created', 'user', 'course_id')]),
        ),
        migrations.AlterIndexTogether(
            name='learnercoursedailyreport',
            index_together=set([('created', 'user', 'course_id'), ('created', 'course_id')]),
        ),
    ]
