# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-04 06:51
from __future__ import unicode_literals

from django.db import migrations
import triboo_analytics.models


class Migration(migrations.Migration):

    dependencies = [
        ('triboo_analytics', '0002_auto_20190903_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydailyreport',
            name='created',
            field=triboo_analytics.models.AutoCreatedField(default=triboo_analytics.models.get_day, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='coursedailyreport',
            name='created',
            field=triboo_analytics.models.AutoCreatedField(default=triboo_analytics.models.get_day, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='iltlearnerreport',
            name='created',
            field=triboo_analytics.models.AutoCreatedField(default=triboo_analytics.models.get_day, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='learnercoursedailyreport',
            name='created',
            field=triboo_analytics.models.AutoCreatedField(default=triboo_analytics.models.get_day, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='learnerdailyreport',
            name='created',
            field=triboo_analytics.models.AutoCreatedField(default=triboo_analytics.models.get_day, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='learnersectionreport',
            name='created',
            field=triboo_analytics.models.AutoCreatedField(default=triboo_analytics.models.get_day, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='learnervisitsdailyreport',
            name='created',
            field=triboo_analytics.models.AutoCreatedField(default=triboo_analytics.models.get_day, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='micrositedailyreport',
            name='created',
            field=triboo_analytics.models.AutoCreatedField(default=triboo_analytics.models.get_day, editable=False, verbose_name='created'),
        ),
    ]
