# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-15 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triboo_analytics', '0005_auto_20190912_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='iltmodule',
            name='course_country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
