# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-27 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triboo_analytics', '0006_iltmodule_course_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='iltlearnerreport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='iltsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
