# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-13 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triboo_analytics', '0007_auto_20190926_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedailyreport',
            name='unique_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
