# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-26 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('triboo_analytics', '0008_coursedailyreport_unique_visitors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearnerSectionReport',
            new_name='LearnerSectionDailyReport',
        ),
        migrations.AlterModelOptions(
            name='learnersectiondailyreport',
            options={'get_latest_by': 'created'},
        ),
        migrations.RenameField(
            model_name='learnersectiondailyreport',
            old_name='time_spent',
            new_name='total_time_spent',
        ),
        migrations.AlterUniqueTogether(
            name='learnersectiondailyreport',
            unique_together=set([('created', 'user', 'course_id', 'section_key')]),
        ),
        migrations.AlterIndexTogether(
            name='learnersectiondailyreport',
            index_together=set([('created', 'course_id'), ('created', 'user', 'course_id', 'section_key')]),
        ),
    ]
