# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-07-16 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('triboo_analytics', '0008_leaderboard_leaderboardview'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_id', models.PositiveIntegerField(db_index=True)),
                ('event_type', models.CharField(max_length=512)),
                ('event_time', models.DateTimeField(db_index=True)),
                ('block_key', opaque_keys.edx.django.models.UsageKeyField(blank=True, max_length=255, null=True)),
                ('course_key', opaque_keys.edx.django.models.CourseKeyField(blank=True, db_index=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='leaderboardactivitylog',
            index_together=set([('user_id', 'event_type'), ('user_id', 'event_type', 'block_key')]),
        ),
    ]
