# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-18 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triboo_analytics', '0009_auto_20200715_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micrositedailyreport',
            name='total_time_spent_on_desktop',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='micrositedailyreport',
            name='total_time_spent_on_mobile',
            field=models.BigIntegerField(default=0),
        ),
    ]
