# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-23 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('triboo_analytics', '0010_auto_20200417_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerBadgeSuccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triboo_analytics.Badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='learnerbadgesuccess',
            unique_together=set([('user', 'badge')]),
        ),
        migrations.AlterIndexTogether(
            name='learnerbadgesuccess',
            index_together=set([('user', 'badge')]),
        ),
    ]
