# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-06-25 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0007_remove_done_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodule',
            name='module_type',
            field=models.CharField(choices=[(b'problem', b'problem'), (b'video', b'video'), (b'html', b'html'), (b'course', b'course'), (b'chapter', b'Section'), (b'sequential', b'Subsection'), (b'library_content', b'Library Content'), (b'ilt', b'ilt')], db_index=True, default=b'problem', max_length=32),
        ),
    ]
