# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-06-23 11:56
from __future__ import unicode_literals

from django.db import migrations
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0008_auto_20190625_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodule',
            name='module_state_key',
            field=opaque_keys.edx.django.models.UsageKeyField(db_column=b'module_id', db_index=True, max_length=255),
        ),
    ]
