# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-03-26 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20190808_0022'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='trackinglog',
            index_together=set([('user_id', 'section', 'time')]),
        ),
    ]
