# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-03 03:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0014_courseoverview_certificate_available_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0002_auto_20190808_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUnenrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name=b'unenrollment date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_overviews.CourseOverview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
