# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-17 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20200326_1136'),
        ('track', '0003_courseunenrollment'),
    ]

    operations = [
    ]
