# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-27 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20200917_0245'),
        ('track', '0004_merge_20200417_0353'),
    ]

    operations = [
    ]
