# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-07 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0021_sso_id_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiproviderconfig',
            name='send_to_registration_first',
            field=models.BooleanField(default=False, help_text="If this option is selected, we'll try to create a new user account when the identity provider authenticated the user but there's no matching user accounts. Otherwise, an error message will be displayed instead."),
        ),
        migrations.AlterField(
            model_name='oauth2providerconfig',
            name='send_to_registration_first',
            field=models.BooleanField(default=False, help_text="If this option is selected, we'll try to create a new user account when the identity provider authenticated the user but there's no matching user accounts. Otherwise, an error message will be displayed instead."),
        ),
        migrations.AlterField(
            model_name='samlproviderconfig',
            name='send_to_registration_first',
            field=models.BooleanField(default=False, help_text="If this option is selected, we'll try to create a new user account when the identity provider authenticated the user but there's no matching user accounts. Otherwise, an error message will be displayed instead."),
        ),
    ]
