# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-16 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_task', '0002_gradereportsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructortask',
            name='task_input',
            field=models.CharField(max_length=2047),
        ),
    ]
