# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-27 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0015_certificatepdfconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcertificate',
            name='download_url',
            field=models.CharField(blank=True, default=b'', max_length=512),
        ),
    ]
