# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-07 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0004_delete_historical_credit_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditprovider',
            name='provider_status_url',
            field=models.URLField(default=b'', help_text='URL from the credit provider where the user can check the status of his or her request for credit.  This is displayed to learners *after* they have requested credit.'),
        ),
    ]
