# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-24 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_auto_20191107_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditrequirementstatus',
            options={'verbose_name_plural': 'Estados de requisitos de cr\xe9dito'},
        ),
        migrations.AlterField(
            model_name='creditconfig',
            name='cache_ttl',
            field=models.PositiveIntegerField(default=0, help_text='Especificado en segundos. Habilite el almacenamiento en cach\xe9 estableciendo esto en un valor mayor que 0.', verbose_name='Tiempo de cach\xe9 para vivir'),
        ),
    ]
