# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-23 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdflexCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EdflexResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField()),
                ('type', models.CharField(db_index=True, max_length=255)),
                ('language', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField()),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('image_url', models.URLField()),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('categories', models.ManyToManyField(related_name='resources', to='external_catalog.EdflexCategory')),
            ],
        ),
        migrations.CreateModel(
            name='EdflexSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('items', models.TextField()),
            ],
        ),
    ]
