# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-30 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edflexresource',
            name='image_url',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='edflexresource',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
