# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-11-10 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_catalog', '0002_auto_20201029_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edflexresource',
            options={'ordering': ['-publication_date', 'title']},
        ),
    ]
