# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-15 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_catalog', '0003_auto_20201110_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='edflexcategory',
            name='language',
            field=models.CharField(default='en', max_length=255),
            preserve_default=False,
        ),
    ]
