# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-12-15 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_catalog', '0004_edflexcategory_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edflexcategory',
            name='category_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='edflexcategory',
            name='language',
            field=models.CharField(default=b'en', max_length=255),
        ),
    ]
