# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-20 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_catalog', '0005_auto_20201215_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edflexresource',
            name='language',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
