# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-20 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_catalog', '0006_auto_20210220_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='edflexcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='edflexcategory',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='edflexresource',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='edflexresource',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='edflexselection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='edflexselection',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
