# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-02-22 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_catalog', '0007_auto_20210220_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edflexresource',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
