# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-03-03 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_catalog', '0008_auto_20210222_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrehanaLanguage',
            fields=[
                ('language_id', models.IntegerField(primary_key=True, serialize=False)),
                ('language', models.CharField(db_index=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrehanaResource',
            fields=[
                ('resource_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('duration', models.IntegerField(default=0, null=True)),
                ('languages', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(max_length=1024, null=True)),
                ('url', models.CharField(max_length=2048, null=True)),
                ('rating', models.FloatField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
