# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-07-12 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_catalog', '0010_auto_20210708_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anderspinkarticle',
            old_name='languages',
            new_name='language',
        ),
    ]
