# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-20 06:21
from __future__ import unicode_literals

import coursewarehistoryextended.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0013_persistentsubsectiongradeoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentCourseProgress',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', coursewarehistoryextended.fields.UnsignedBigIntAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(max_length=255)),
                ('percent_progress', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='persistentcourseprogress',
            unique_together=set([('course_id', 'user_id')]),
        ),
    ]
