# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-11 08:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0018_auto_20190328_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sections', models.CharField(default=None, max_length=255, null=True)),
                ('description', models.TextField(default=None)),
                ('approved', models.NullBooleanField(default=None)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_requests', to='student.CourseEnrollment')),
                ('instructor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_waiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
