# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-19 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_userprofile_lt_ilt_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lt_ilt_supervisor',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'ILT Supervisor'),
        ),
    ]
