# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-21 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20190819_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lt_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Commercial Zone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lt_sub_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Commercial Region'),
        ),
    ]
