# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-18 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20190821_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='gradebook_edit',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
