# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-07 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_courseenrollment_gradebook_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lt_ilt_supervisor',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name=b'ILT Supervisor'),
        ),
    ]
