# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-09-24 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20200407_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lt_level',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name=b'Level'),
        ),
    ]
