# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-15 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20200924_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='service_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]